# Generated by Django 4.1.5 on 2023-02-04 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_alter_student_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='teacher',
            field=models.ManyToManyField(related_name='student', to='school.teacher', verbose_name='Учитель'),
        ),
    ]
